parameters:
    product.headers:
        code: 'Product Code'
        name: 'Product Name'
        description: 'Product Description'
        stock: 'Stock'
        price: 'Cost in GBP'
        discontinued: 'Discontinued'
    product.entity: 'AppBundle:Product'