# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.csv_validator:
          class: AppBundle\Helpers\CsvValidator
          arguments: ["%product.headers%"]
    app.new_product_writer:
          class: AppBundle\Writer\NewProductWriter
          arguments: ['@doctrine.orm.entity_manager', '%product.entity%']
